# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYjagBwjWgefIh1lA0uKfQMPi_uYTSTs
"""

!pip install -q git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install -y ffmpeg

from google.colab import files
uploaded = files.upload()

import whisper

# تحميل نموذج Whisper
model = whisper.load_model("base")  # فيه خيارات ثانية زي "small", "medium", "large"

# تحويل الملف الصوتي إلى نص
filename = list(uploaded.keys())[0]  # اسم الملف اللي رفعتيه
result=model.transcribe(filename, language="ar")  # نحدد اللغة العربية

# طباعة النص الناتج
print("📝 النص المحوّل:", result['text'])

!pip install openai

!pip install cohere

import cohere

# 🔑 حطي مفتاحك هنا
co = cohere.Client("wb95Vsxw6tUlVQGlg8rSQpA4ikepK4p2dLraZOfx")

# 📝 هنا بنحط النص اللي طلع من Whisper (مثلاً)
user_input = result['text']

# ✨ توليد الرد من Cohere
response = co.generate(
    model='command-r-plus',  # تقدر تغيرين للنموذج المتاح عندك
    prompt=f"رد بلغة لطيفة على: {user_input}",
    max_tokens=100
)

# 📢 طباعة الرد
reply = response.generations[0].text.strip()
print("🤖 رد Cohere:", reply)

!pip install gTTS

from gtts import gTTS
from IPython.display import Audio

tts = gTTS(reply, lang='ar')
tts.save("response.mp3")
Audio("response.mp3", autoplay=True)